#!/usr/bin/env bash

viewer_openssl_supports () {
    command -v "openssl" >/dev/null || return 1
    case "$1" in
        *.pem|*.crt|*.cer) return 0
    esac
    return 1
}

viewer_openssl_process () {
    [ -n "$1" ] && openssl x509 -noout -text -certopt no_header,no_version,no_signame,no_pubkey,no_sigdump -in "$1"
}

BATPIPE_VIEWERS+=("openssl")
